version: "3.9"

services:
  app:
    build: .
    container_name: weddingplanner-app
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - mysql
    env_file:
      - .env.docker

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
    MYSQL__ROOT_USER: root
    MYSQL_ROOT_PASSWORD: XPqZhkGAqUPBLVmiC46d
    MYSQL_DATABASE: weddingplanner-db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    restart: always

volumes:
  mysql-data:
