version: "3.9"

services:
  app:
    build: .
    container_name: weddingplanner-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=XPqZhkGAqUPBLVmiC46d
      - DB_NAME=weddingplanner-db
      - DB_PORT=3306
      - DATABASE_URL=mysql://root:XPqZhkGAqUPBLVmiC46d@localhost:3306/weddingplanner-db

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: XPqZhkGAqUPBLVmiC46d
      MYSQL_DATABASE: weddingplanner-db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 # Correcte plaatsing van 'command'
    restart: always

volumes:
  mysql-data:
