name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x' 

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build 

    - name: Run tests
      run: npm test 

      -- name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: . # Map van het project (de root in dit geval)
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Geheim token voor authenticatie op SonarCloud
